/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ThiSideDrawer {
        "hide": () => Promise<void>;
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface ThiSpinner {
    }
    interface ThiStockFinder {
    }
    interface ThiStockPrice {
        "stockSymbol": string;
    }
    interface ThiTooltip {
        "text": string;
    }
}
declare global {
    interface HTMLThiSideDrawerElement extends Components.ThiSideDrawer, HTMLStencilElement {
    }
    var HTMLThiSideDrawerElement: {
        prototype: HTMLThiSideDrawerElement;
        new (): HTMLThiSideDrawerElement;
    };
    interface HTMLThiSpinnerElement extends Components.ThiSpinner, HTMLStencilElement {
    }
    var HTMLThiSpinnerElement: {
        prototype: HTMLThiSpinnerElement;
        new (): HTMLThiSpinnerElement;
    };
    interface HTMLThiStockFinderElement extends Components.ThiStockFinder, HTMLStencilElement {
    }
    var HTMLThiStockFinderElement: {
        prototype: HTMLThiStockFinderElement;
        new (): HTMLThiStockFinderElement;
    };
    interface HTMLThiStockPriceElement extends Components.ThiStockPrice, HTMLStencilElement {
    }
    var HTMLThiStockPriceElement: {
        prototype: HTMLThiStockPriceElement;
        new (): HTMLThiStockPriceElement;
    };
    interface HTMLThiTooltipElement extends Components.ThiTooltip, HTMLStencilElement {
    }
    var HTMLThiTooltipElement: {
        prototype: HTMLThiTooltipElement;
        new (): HTMLThiTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "thi-side-drawer": HTMLThiSideDrawerElement;
        "thi-spinner": HTMLThiSpinnerElement;
        "thi-stock-finder": HTMLThiStockFinderElement;
        "thi-stock-price": HTMLThiStockPriceElement;
        "thi-tooltip": HTMLThiTooltipElement;
    }
}
declare namespace LocalJSX {
    interface ThiSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface ThiSpinner {
    }
    interface ThiStockFinder {
        "onThiSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface ThiStockPrice {
        "stockSymbol"?: string;
    }
    interface ThiTooltip {
        "text"?: string;
    }
    interface IntrinsicElements {
        "thi-side-drawer": ThiSideDrawer;
        "thi-spinner": ThiSpinner;
        "thi-stock-finder": ThiStockFinder;
        "thi-stock-price": ThiStockPrice;
        "thi-tooltip": ThiTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "thi-side-drawer": LocalJSX.ThiSideDrawer & JSXBase.HTMLAttributes<HTMLThiSideDrawerElement>;
            "thi-spinner": LocalJSX.ThiSpinner & JSXBase.HTMLAttributes<HTMLThiSpinnerElement>;
            "thi-stock-finder": LocalJSX.ThiStockFinder & JSXBase.HTMLAttributes<HTMLThiStockFinderElement>;
            "thi-stock-price": LocalJSX.ThiStockPrice & JSXBase.HTMLAttributes<HTMLThiStockPriceElement>;
            "thi-tooltip": LocalJSX.ThiTooltip & JSXBase.HTMLAttributes<HTMLThiTooltipElement>;
        }
    }
}
